spring:
  datasource:
    url: jdbc:mysql://47.113.147.222:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 47.113.147.222:8848

  application:
    name: user-service

  mail:
    host: smtp.qq.com
    password: mmjxlwoskgyncacj
    username: 495096496@qq.com

server:
  port: 8004