spring:
  datasource:
    url: jdbc:mysql://47.113.147.222:3306/goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: goods
    password: goods
    driver-class-name: com.mysql.cj.jdbc.Driver


  cloud:
    nacos:
      discovery:
        server-addr: 47.113.147.222:8848

  application:
    name: goods-service


server:
  port: 8002