spring:
  datasource:
    url: jdbc:mysql://47.113.147.222:3306/ad?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ad
    password: ad
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 47.113.147.222:8848

  application:
    name: AD-service

server:
  port: 8001