spring:
  datasource:
    url: jdbc:mysql://47.113.147.222:3306/house?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: house
    password: house
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 47.113.147.222:8848

  application:
    name: house-service

server:
  port: 8003